---
- name: Set OS kernel parameter semopm
  sysctl:
    sysctl_file: /etc/sysctl.d/01-oracle.conf
    sysctl_set: true
    reload: true
    name: kernel.sem
    value: 250 32000 100 128
    state: present

- name: Set OS kernel parameter shmall
  sysctl:
    sysctl_file: /etc/sysctl.d/01-oracle.conf
    sysctl_set: true
    reload: true
    name: kernel.shmall
    value: 2251799813685247
    state: present

- name: Set OS kernel parameter rmem_default
  sysctl:
    sysctl_file: /etc/sysctl.d/01-oracle.conf
    sysctl_set: true
    reload: true
    name: net.core.rmem_default
    value: 262144
    state: present

- name: Set OS kernel parameter rmem_max
  sysctl:
    sysctl_file: /etc/sysctl.d/01-oracle.conf
    sysctl_set: true
    reload: true
    name: net.core.rmem_max
    value: 4194304
    state: present

- name: Set OS kernel parameter wmem_default
  sysctl:
    sysctl_file: /etc/sysctl.d/01-oracle.conf
    sysctl_set: true
    reload: true
    name: net.core.wmem_default
    value: 262144
    state: present

- name: Set OS kernel parameter wmem_max
  sysctl:
    sysctl_file: /etc/sysctl.d/01-oracle.conf
    sysctl_set: true
    reload: true
    name: net.core.wmem_max
    value: 1048576
    state: present

- name: Set OS kernel parameter aio-max-nr
  sysctl:
    sysctl_file: /etc/sysctl.d/01-oracle.conf
    sysctl_set: true
    reload: true
    name: fs.aio-max-nr
    value: 1048576
    state: present



